server:
  port: 8083

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jlr2/microservicio-configuracionlocal.git
          force-pull: true
          clone-on-start: true
          username:
          password:
          default-label: main

          repos:
            local:
              uri: https://github.com/jlr2/microservicio-configuracionlocal.git
              clone-on-start: true
              username:
              password:
              label: main
